version: "3.8"
services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./postgres.properties
    ports:
      - $POSTGRES_EXPOSE_PORT:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pulsar-app:
    image: sevketriza/pulsar-app:latest
    depends_on:
      - postgresdb
    restart: on-failure
    env_file: ./pulsar-app.properties
    ports:
      - $API_EXPOSE_PORT:8081
    stdin_open: true
    tty: true
  pulsar-ui:
    image: sevketriza/pulsar-ui:latest
    depends_on:
      - pulsar-app
    restart: on-failure
    env_file: ./pulsar-ui.properties
    ports:
      - $UI_EXPOSE_PORT:80
volumes:
  pgdata:
